### ISSUE TITLE
Support linking against system liblzma

### ISSUE THREAD

**Issue by infinity0** [alexcrichton/xz2-rs#16]
Work around is to do, e.g., for rustc:

~~~~
echo 'fn main() { println!("cargo:rustc-link-lib=lzma"); }' > src/vendor/lzma-sys/build.rs
~~~~

**Comment by alexcrichton** [comment]
Sounds good to me! PRs are of course always welcome!

**Comment by infinity0** [comment]
Sorry - I would have, but I was not sure the best way to add this behaviour into the existing script, and wasn't clear what the rust "conventions" are in this area.

How about "if the xz-* directory doesn't exist, link dynamically, else do (the existing behaviour)"?

**Comment by alexcrichton** [comment]
Oh typically the convention is to just run pkg-config or something like that at the top of the script, if it succeeds everything else is skipped otherwise all the other logic continues to execute.
