### ISSUE TITLE
Handle multi-streams files gracefully

### ISSUE THREAD

**Issue by Fabiensk** [alexcrichton/xz2-rs#25]
I noticed a tricky case that may be related to #13: when a file contains [several streams](https://github.com/alexcrichton/xz2-rs/blob/master/lzma-sys/xz-5.2.3/doc/xz-file-format.txt#L245) (for example if it was created with _pxz_, a parallel compressor).
From what I understand, to handle such a case, it is possible to do the following:

- open the file
- loop:
  - keep the current offset in the file (let call it `offset_before`)
  - create a XzDecoder for the current xz stream
  - loop to decompress this stream by calling `read`
  - if it ends with an error and if some bytes were read for this stream, then try to move to the start of the next stream by seeking in the file to `offset_before + total_in()` and skipping all the null bytes (optional stream padding). If there is an error but no byte was read, then it is really an error and we stop everything here.

I think it would be better if the case of the multi-stream files was transparently handled by XzDecoder. 
**edit**: In fact, now I think it would be mandatory for non-seekable files (like Unix pipes)

**Comment by alexcrichton** [comment]
Interesting! This sort of sounds like the `MultiGzDecoder` in `flate2` where gz streams can be concatenated to create one file that actually has a few inside of it. I think it'd definitely be ok to add a dedicated struct for handling this case!

**Comment by Fabiensk** [comment]
Sorry for the late reply. I don't get what would be the advantage of creating three new structs (related to `bufread::XzDecoder`, `read::XzDecoder` and `write::XzDecoder`) compared to adding builder methods (with distinct flags for the liblzma decoder) to the existing structs. In `MultiGzDecoder`, there is specific code to manage the multiple streams, but for xz everything is managed by liblzma.

I did create new structs, but in the end it means that the functions (for `Read` and `Write`) will have to be implemented, and either they will contain the same code than the single-stream ones, or they will forward to new shared structs/functions.

(I'm not familiar with how modules and types should be organized in Rust, I'm more familiar with Java/C++/Python; also, it's not a blocker for any project I have, I'm just playing a bit with Rust)

**Comment by alexcrichton** [comment]
Oh ok sure yeah that makes sense. I think so long as it's an opt-in I'm down for that, if it's with a new type or just a flag that sounds fine.

**Comment by Fabiensk** [comment]
Has evolved into pull request #31, following the two last comments.
