### ISSUE TITLE
Support Visual Studio 2017

### ISSUE THREAD

**Issue by abonander** [alexcrichton/xz2-rs#29]
The [xz utils upstream git](https://git.tukaani.org/?p=xz.git;a=tree;f=windows;h=bafeef43ec1e5647acb3090d9c5ede09889ac118;hb=HEAD) has a solution/`vcxproj` file for VS2017 now.

**Comment by alexcrichton** [comment]
I'd be down for using a submodule!

**Comment by abonander** [comment]
Curiously, the Git link I posted above as well as the official Gitweb link on the xz utils site both 404 now. I haven't tried cloning the repository. There is also an unofficial mirror here on Github: https://github.com/xz-mirror/xz

However, the 5.2.4 stable release has the vs2017 solution in it, so updating could be as simple as overwriting with the stable release. 

@alexcrichton I can open a PR for one or the other, which do you prefer?

**Comment by alexcrichton** [comment]
Ah either way's fine by me, pointing to a github submodule should likely be fine

**Comment by abonander** [comment]
I ran into a bit of a hangup: it looks like VS2017 projects explicitly link against a very specific version of the Windows SDK and there's no way to loosen that requirement: https://developercommunity.visualstudio.com/content/problem/140294/windowstargetplatformversion-makes-it-impossible-t.html

The latest HEAD on the `v5.2` branch of the xz git links against `10.0.15063.0`. The build fails if you don't have that specific version installed. You can fix that easily enough in the Visual Studio Installer but it's still a manual process. It also works fine if you manually update `liblzma.vcxproj` with the correct `WindowsTargetPlatformVersion` but there's no way to set it to a generic `10.0` version like you could do for Windows 8.1.

I don't know how we want to solve this in `build.rs` if we want to at all. We could leave it at the set version and instruct users to install that specific version of the Windows SDK, or otherwise wait for the Visual Studio team to fix the issue, which the last comment on that thread (submitted 15 hours ago) suggests that they're working on it.

**Comment by alexcrichton** [comment]
One possibility would be to ditch the native build system entirely and use a crate like `cc` perhaps?

**Comment by abonander** [comment]
@alexcrichton looking through the makefiles, that seems to be doable provided we pick some configuration defaults and hardcode them into the `cc` invocations. A lot of the work will be manually enumerating the source files since there's a number of them, although I think we could use `read_dir()` for most of them.

**Comment by abonander** [comment]
@alexcrichton the most difficult bit is the OS detection that autoconf does; it selects the right versions of two functions, one to get the number of CPUs in the system and the other to get the amount of available RAM, used to tune the encoder/decoder. We can implement the former with a shim around `num_cpus` maybe, so we don't have to run all that logic in a build script. However, I can't find a crate that provides a simple function for the latter.

**Comment by abonander** [comment]
It looks to be possible with ifdefs to short-circuit the latter so it returns a constant amount, I think it's just used to determine how large a buffer to allocate.

**Comment by abonander** [comment]
Actually it looks like neither call is used directly in `liblzma`, it's mostly helpers for the command-line tools. We can just not build those or include their headers then. Unfortunately, those are buried in directories full of source files and headers we *do* need, so manual filtering is still in order.

**Comment by shssoichiro** [comment]
Would it be possible to publish a new version with this fix? I am still unable to install rustup-toolchain-install-master even after the suggested workaround in this thread of installing the specific Windows SDK version.

**Comment by alexcrichton** [comment]
Sure thing! Should be done now
