### ISSUE TITLE
Build failure when cross-compiling for FreeBSD

### ISSUE THREAD

**Issue by ranma42** [alexcrichton/xz2-rs#4]
Using xz2 in a FreeBSD cross-build environment results in the following error:
https://travis-ci.org/rust-lang-nursery/rustup.rs/jobs/231443067#L1088

**Comment by alexcrichton** [comment]
Looks like there's a new release of xz, 5.2.3. with the news of:

> Use of external SHA-256 code is now disabled by default.
  It can still be enabled by passing --enable-external-sha256
  to configure.

Looks like that's exactly what we want! I'll test it out.
