### ISSUE TITLE
Opinions about applying rustfmt

### ISSUE THREAD

**Issue by maoe** [alexcrichton/xz2-rs#41]
While I'm working on #39 I found a bit annoying that the code hasn't been formatted using rustfmt.

I can of course either

* disable rustfmt when working on this codebase and manually format new code, or
* write code with rustfmt but check in only non-stylistic changes

but neither is satisfactory. Are you happy to accept rustfmt changes? If so I'll make a PR.

**Comment by alexcrichton** [comment]
Having a rustfmt PR sounds great to me!

**Comment by maoe** [comment]
Great, just made #42.
