### ISSUE TITLE
lzma-sys v0.1.13 Fails to build on mingw

### ISSUE THREAD

**Issue by kinnison** [alexcrichton/xz2-rs#45]
Hi,

Recently we were trying to do a Rustup release and encountered an issue where lzma-sys 0.1.13 wouldn't build on our Appveyor mingw builders.  You can find a log here: https://ci.appveyor.com/project/rust-lang-libs/rustup-rs/builds/22849436/job/d3upd7t46kmp4154

Reverting to 0.1.10 allowed our builds to proceed.

I am not necessarily in a position to bisect since I don't have a windows/mingw environment to hand, but if there's some way I can assist anyhow, please let me know and I'll do my best.

D.

**Comment by alexcrichton** [comment]
I think I managed to fix this in https://github.com/alexcrichton/xz2-rs/commit/c04d0d1e3afec811705d828fee9f380ac286e1d1 (and add tests!)
