### ISSUE TITLE
Build tied to specific platform toolset on windows

### ISSUE THREAD

**Issue by Diggsey** [alexcrichton/xz2-rs#6]
When building for `-msvc` with the VC++ 2015 build tools, the build fails:
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\diggs\Projects\rustup-rs\target\debug\build\lzma-sys-8de572d4e0ca373d\out\build\windows\liblzma.vcxproj]

The project should probably not be tied to a specific platform toolset version.

**Comment by alexcrichton** [comment]
Unfortunately I don't really know anything about vcxproj files and whatnot, is there a way to fix this?

**Comment by Diggsey** [comment]
Yep, you just need to pass `/p:PlatformToolset=v140/v120/v110/v100/v90` to the `msbuild` invocation, depending on the version of the VC++ build tools / visual studio.

**Comment by alexcrichton** [comment]
Ah ok, PRs to do this are of course always welcome!
