### ISSUE TITLE
lzma-sys: features=["static"]

### ISSUE THREAD

**Issue by brainstorm** [alexcrichton/xz2-rs#62]
Would it be possible to have `static` feature for this lib like libz-sys does? Same idea as https://github.com/alexcrichton/bzip2-rs/issues/56 ... working on a project that requires all MUSL deps to be static :-S

/cc https://github.com/alexcrichton/bzip2-rs/issues/56

**Comment by brainstorm** [comment]
@alexcrichton Would you mind bumping up the version for `lzma-sys` and pushing it to crates.io? I forgot about that on the PR :/

I think this change can be generally useful to other rustaceans and justifies a version change, IMHO.

**Comment by alexcrichton** [comment]
Sure thing, done now!
