### ISSUE TITLE
"lzma data error"

### ISSUE THREAD

**Issue by Yuri6037** [alexcrichton/xz2-rs#73]
No matter what I try and no matter what I do the decoder always throws "lzma data error". Sample code:

```rust
const READ_BLOCK_SIZE: usize = 8192;

fn block_based_inflate2(input: &mut dyn Read, output: &mut dyn Write) -> io::Result<()>
{
    let mut decoder = match Stream::new_stream_decoder(u32::MAX, xz::stream::CONCATENATED)
    {
        Err(e) => return Err(io::Error::new(io::ErrorKind::InvalidData, format!("[BPX] inflate error: {}", e))),
        Ok(v) => v
    };
    let mut idata: [u8; READ_BLOCK_SIZE] = [0; READ_BLOCK_SIZE];
    let mut status = xz::stream::Status::MemNeeded;
    let mut res = input.read(&mut idata)?;

    while res > 0
    {
        println!("{}", res);
        let mut odata: Vec<u8> = Vec::with_capacity(READ_BLOCK_SIZE * 2);
        match decoder.process_vec(&idata[0..res], &mut odata, xz::stream::Action::Run)
        {
            Ok(_) => (),
            Err(e) => return Err(io::Error::new(io::ErrorKind::InvalidData, format!("[BPX] inflate error: {}", e)))
        }
        output.write(&odata)?;
        res = input.read(&mut idata)?;
    }
    while status != xz::stream::Status::StreamEnd
    {
        let mut odata: Vec<u8> = Vec::with_capacity(READ_BLOCK_SIZE * 2);
        match decoder.process_vec(&idata[0..0], &mut odata, xz::stream::Action::Finish)
        {
            Ok(s) => status = s,
            Err(e) => return Err(io::Error::new(io::ErrorKind::InvalidData, format!("[BPX] inflate error: {}", e)))
        }
        output.write(&odata)?;
    }
    return Ok(());
}

fn main() -> io::Result<()>
{
    let mut out = std::fs::File::create(Path::new("./file.jpg"))?;
    let mut i = std::fs::File::open(Path::new("./file.jpg.xz"))?;
    block_based_inflate2(&mut i, &mut out)?;
    return Ok(());
}
```

Just compress a jpg file using `xz --compress file.jpg` then run the program. No matter what Jpeg you give it's unreadable!! You can however decompress it with xz.

Why is the decoder broken?

EDIT: I found a way to fix it however I found something really strange in return: if you give the same buffer size for the output data as for the input you get "lzma data error". The size of the output buffer must be size of input buffer * 2.

In my tests, no matter what size I gave it failed with "lzma data error" unless I give it size of input buffer * 2. Is there any reason for that? Looking at LZMA example it should not be needed.

**Comment by alexcrichton** [comment]
Working with the raw `Stream` type is unfortunately often difficult and requires a lot of care. It has to do mostly with the behavior of the upstream library itself, so I'm not really the person to ask about. I'd recommend searching around for usage of the C library if you'd like to see why buffers need to be certain sizes.
