### ISSUE TITLE
xz2-rs may be unsound due to calls to `getenv`

### ISSUE THREAD

**Issue by xerxes12354** [alexcrichton/xz2-rs#76]
I was looking at the time crate wondering why the [time crate didn't give offsets](https://github.com/time-rs/time/issues/293), and I stumbled upon [this thread on Internals](https://internals.rust-lang.org/t/function-to-hold-lock-on-execution-environment-for-ffi/13702/22). This seems like a big problem so I went looking for FFI crates where this could be a problem.

liblzma uses getenv https://github.com/kobolabs/liblzma/blob/87b7682ce4b1c849504e2b3641cebaad62aaef87/lib/getopt.c#L250, it looks like this wrapper has a data race when `set_env` is called in another thread.

**Comment by alexcrichton** [comment]
Thanks for the report, but you can't reasonably expect all Rust projects which call C to magically handle this. Opening an issue on each separate repository I don't think is productive.

**Comment by xerxes12354** [comment]
This exposes an unsound API to safe code, violating safety guarantees.
