### ISSUE TITLE
Stream::process_vec() produces no output

### ISSUE THREAD

**Issue by nabeelomer** [alexcrichton/xz2-rs#8]
```rust
let mut strm = Stream::new_easy_encoder(9, Check::Sha256).unwrap();
let rawbuf = read_n(file, to); //Read `to (u64)` bytes from `file` and store in `rawbuf (Vec<u8>)`
let mut retvec: Vec<u8> = Vec::new();
strm.process_vec(rawbuf.as_slice(), &mut retvec, Action::SyncFlush).unwrap();
```
In the code above, `retvec` contains no data even though `rawbuf` does.

**Comment by alexcrichton** [comment]
Ah you'll need to use `with_capacity` or somehow make sure the vec has capacity, [from the docs](https://docs.rs/xz2/0.1.3/xz2/stream/struct.Stream.html#method.process_vec)

> This function will use the extra capacity of output as a destination for bytes to be placed. The length of output will automatically get updated after the operation has completed.

**Comment by nabeelomer** [comment]
Thanks.
