### ISSUE TITLE
Release xz2 0.1.7?

### ISSUE THREAD

**Issue by indygreg** [alexcrichton/xz2-rs#97]
It has been a few... years since xz2 0.1.6. During that time, some dependencies were updated and the `static` crate feature was added.

The latter is interesting to me because I inadvertently slipped a reference to a `/usr/local/opt/xz/lib/liblzma.5.dylib` in some macOS Rust binaries I built in GitHub Actions. I can presumably work around this by forcing the linker to use the liblzma inside the macOS SDK. But it sure is tempting to lean on a `static` crate feature and eliminate the possibility of the shared library dependency.

Are there any plans for a 0.1.7 release? Is there anything I could do to help with one?

**Comment by alexcrichton** [comment]
Sure thing I've just published. I haven't really touched this crate in quite some time and would be happy to hand it off if you're interested as well.

**Comment by indygreg** [comment]
Thank you for publishing 0.1.7! I just upgraded to it and it seems to _just work_.

While I'm certainly technically capable of taking stewardship of this crate, I'm not the greatest maintainer in the world. My presence is intermittent (ex: the fact it took me 20 days to reply to you). I'd encourage you to find someone with more availability/interest than me. But if you can't find someone and/or desperately want to hand off ownership, I could shoulder that burden for you.

**Comment by alexcrichton** [comment]
No worries, just figured I'd ask
